### PR TITLE
Wrap install script in function to ensure it's downloaded fully

### PR DESCRIPTION
**Pull request by arp242**
Otherwise network errors half-way will run half a script.

### CODE REVIEW

**Comment by arp242** [comment]
Diff is probably best viewed ignoring whitespace btw: https://github.com/team-video/aviary.sh/pull/3/files?diff=unified&w=1

**Comment by dougbrunton** [comment]
Thanks for the PR.  Part of me wonders if we should drop the download and execute part of the instructions, and ask folks to download and inspect the script before running it (there's a part of a conversation happening about that over here https://github.com/team-video/aviary.sh/issues/2#issuecomment-649818516 - but maybe that should be it's own issue).

If we decide to keep it, something like what you propose here seems like the right thing - thanks again.

**Comment by arp242** [comment]
I don't think it's that big of a deal to be honest; I actually wrote an article about this a while ago, in case you're interested: https://www.arp242.net/curl-to-sh.html

**Comment by dougbrunton** [comment]
I appreciate that sentiment, and I mostly agree with it.  I think if we were to change the install instructions it would include verifying the sha sum of the contents of the install script.

But back to the topic at hand!  In other places in the aviary code base functions are explicitly declared with the `function` keyword.  Other than that, I think this is good to go.

**Comment by arp242** [comment]
Oh sure, I added `function`.

**Comment by dougbrunton** [comment]
Thanks.  @dchester - is this good to merge?

**Comment by dchester** [comment]
Yes, thanks!

**Pull request merged**
